import type { MetadataDetail, MetadataProperty } from '@/lib/ekuiper/types';

/**
 * Built-in connector property catalogs for eKuiper sources, sinks, and connections.
 * These serve as authoritative fallbacks when eKuiper returns 404 (e.g. plugins like SQL/Kafka)
 * or when eKuiper returns metadata items without a schema definition.
 */

export const BUILTIN_SOURCE_PROPERTIES: Record<string, MetadataProperty[]> = {
  sql: [
    {
      name: 'url',
      type: 'string',
      control: 'text',
      optional: false,
      default: 'mysql://root:password@127.0.0.1:3306/test',
      label: { en: 'Database URL', zh: '数据库连接 URL' },
      hint: { en: 'Database connection URL string (e.g. mysql://user:pass@host:port/db, postgres://..., sqlserver://...)', zh: '数据库连接字符串' },
    },
    {
      name: 'interval',
      type: 'int',
      control: 'text',
      optional: true,
      default: 1000,
      label: { en: 'Query Interval (ms)', zh: '查询间隔 (毫秒)' },
      hint: { en: 'Periodic query interval in milliseconds for lookup or scan', zh: '轮询查询间隔毫秒' },
    },
    {
      name: 'table',
      type: 'string',
      control: 'text',
      optional: true,
      default: '',
      label: { en: 'Table Name', zh: '表名' },
      hint: { en: 'Target SQL table name to query from', zh: '查询的 SQL 表名' },
    },
    {
      name: 'internalQueryUrl',
      type: 'string',
      control: 'text',
      optional: true,
      default: '',
      label: { en: 'Internal Query URL', zh: '内部查询 URL' },
      hint: { en: 'Optional internal query endpoint override', zh: '可选的内部查询 URL' },
    },
  ],
  mqtt: [
    {
      name: 'server',
      type: 'string',
      control: 'text',
      optional: false,
      default: 'tcp://127.0.0.1:1883',
      label: { en: 'MQTT Broker Server', zh: 'MQTT 服务器地址' },
      hint: { en: 'The broker address of the MQTT server, e.g. tcp://127.0.0.1:1883', zh: 'MQTT 服务器地址，例如 tcp://127.0.0.1:1883' },
    },
    {
      name: 'protocolVersion',
      type: 'string',
      control: 'select',
      optional: true,
      default: '3.1.1',
      values: ['3.1.1', '3.1', '5.0'],
      label: { en: 'Protocol Version', zh: '协议版本' },
      hint: { en: 'MQTT protocol specification version', zh: 'MQTT 协议版本' },
    },
    {
      name: 'clientid',
      type: 'string',
      control: 'text',
      optional: true,
      default: '',
      label: { en: 'Client ID', zh: '客户端 ID' },
      hint: { en: 'MQTT client identification string', zh: '客户端唯一标识' },
    },
    {
      name: 'username',
      type: 'string',
      control: 'text',
      optional: true,
      default: '',
      label: { en: 'Username', zh: '用户名' },
    },
    {
      name: 'password',
      type: 'string',
      control: 'text',
      optional: true,
      default: '',
      label: { en: 'Password', zh: '密码' },
    },
    {
      name: 'qos',
      type: 'int',
      control: 'select',
      optional: true,
      default: 1,
      values: [0, 1, 2],
      label: { en: 'QoS', zh: '服务质量' },
    },
    {
      name: 'insecureSkipVerify',
      type: 'bool',
      control: 'radio',
      optional: true,
      default: false,
      label: { en: 'Skip TLS Verify', zh: '跳过 TLS 证书检查' },
    },
    {
      name: 'certificationPath',
      type: 'string',
      control: 'text',
      optional: true,
      default: '',
      label: { en: 'Cert Path', zh: '证书路径' },
    },
    {
      name: 'privateKeyPath',
      type: 'string',
      control: 'text',
      optional: true,
      default: '',
      label: { en: 'Private Key Path', zh: '私钥路径' },
    },
    {
      name: 'rootCaPath',
      type: 'string',
      control: 'text',
      optional: true,
      default: '',
      label: { en: 'Root CA Path', zh: '根证书路径' },
    },
    {
      name: 'bufferLength',
      type: 'int',
      control: 'text',
      optional: true,
      default: 1024,
      label: { en: 'Buffer Length', zh: '缓冲长度' },
    },
  ],
  kafka: [
    {
      name: 'brokers',
      type: 'string',
      control: 'text',
      optional: false,
      default: '127.0.0.1:9092',
      label: { en: 'Kafka Brokers', zh: 'Kafka 服务节点' },
      hint: { en: 'Comma-separated broker list, e.g. 127.0.0.1:9092,127.0.0.1:9093', zh: '逗号分隔的服务节点列表' },
    },
    {
      name: 'topic',
      type: 'string',
      control: 'text',
      optional: false,
      default: '',
      label: { en: 'Topic', zh: '订阅主题' },
    },
    {
      name: 'groupid',
      type: 'string',
      control: 'text',
      optional: true,
      default: 'ekuiper_group',
      label: { en: 'Consumer Group ID', zh: '消费组 ID' },
    },
    {
      name: 'saslAuthType',
      type: 'string',
      control: 'select',
      optional: true,
      default: 'none',
      values: ['none', 'plain', 'scram-sha-256', 'scram-sha-512'],
      label: { en: 'SASL Auth Type', zh: '认证机制' },
    },
    {
      name: 'saslUserName',
      type: 'string',
      control: 'text',
      optional: true,
      default: '',
      label: { en: 'SASL Username', zh: 'SASL 用户名' },
    },
    {
      name: 'saslPassword',
      type: 'string',
      control: 'text',
      optional: true,
      default: '',
      label: { en: 'SASL Password', zh: 'SASL 密码' },
    },
    {
      name: 'insecureSkipVerify',
      type: 'bool',
      control: 'radio',
      optional: true,
      default: false,
      label: { en: 'Skip TLS Verify', zh: '跳过 TLS 检查' },
    },
  ],
  edgex: [
    {
      name: 'protocol',
      type: 'string',
      control: 'select',
      optional: true,
      default: 'tcp',
      values: ['tcp', 'http', 'https'],
      label: { en: 'Protocol', zh: '协议' },
    },
    {
      name: 'server',
      type: 'string',
      control: 'text',
      optional: false,
      default: '127.0.0.1',
      label: { en: 'Server Host', zh: '服务器地址' },
    },
    {
      name: 'port',
      type: 'int',
      control: 'text',
      optional: false,
      default: 5566,
      label: { en: 'Port', zh: '端口' },
    },
    {
      name: 'type',
      type: 'string',
      control: 'select',
      optional: false,
      default: 'redis',
      values: ['redis', 'mqtt', 'zero'],
      label: { en: 'Message Bus Type', zh: '总线类型' },
    },
    {
      name: 'topic',
      type: 'string',
      control: 'text',
      optional: true,
      default: 'rules-events',
      label: { en: 'Topic', zh: '主题' },
    },
  ],
  httppull: [
    {
      name: 'url',
      type: 'string',
      control: 'text',
      optional: false,
      default: 'http://127.0.0.1:8080/api',
      label: { en: 'Endpoint URL', zh: '请求 URL' },
    },
    {
      name: 'method',
      type: 'string',
      control: 'select',
      optional: true,
      default: 'GET',
      values: ['GET', 'POST', 'PUT', 'DELETE'],
      label: { en: 'Method', zh: '请求方法' },
    },
    {
      name: 'interval',
      type: 'int',
      control: 'text',
      optional: true,
      default: 1000,
      label: { en: 'Pull Interval (ms)', zh: '拉取间隔 (毫秒)' },
    },
    {
      name: 'timeout',
      type: 'int',
      control: 'text',
      optional: true,
      default: 5000,
      label: { en: 'Request Timeout (ms)', zh: '超时时间 (毫秒)' },
    },
    {
      name: 'headers',
      type: 'object',
      control: 'list',
      optional: true,
      label: { en: 'HTTP Headers', zh: 'HTTP 请求头' },
    },
    {
      name: 'insecureSkipVerify',
      type: 'bool',
      control: 'radio',
      optional: true,
      default: false,
      label: { en: 'Skip TLS Verify', zh: '跳过 TLS 检查' },
    },
  ],
  http: [
    {
      name: 'url',
      type: 'string',
      control: 'text',
      optional: false,
      default: 'http://127.0.0.1:8080/api',
      label: { en: 'Endpoint URL', zh: '请求 URL' },
    },
    {
      name: 'method',
      type: 'string',
      control: 'select',
      optional: true,
      default: 'GET',
      values: ['GET', 'POST', 'PUT', 'DELETE'],
      label: { en: 'Method', zh: '请求方法' },
    },
    {
      name: 'interval',
      type: 'int',
      control: 'text',
      optional: true,
      default: 1000,
      label: { en: 'Pull Interval (ms)', zh: '拉取间隔' },
    },
  ],
  httppush: [
    {
      name: 'port',
      type: 'int',
      control: 'text',
      optional: false,
      default: 9090,
      label: { en: 'Listen Port', zh: '监听端口' },
    },
    {
      name: 'path',
      type: 'string',
      control: 'text',
      optional: true,
      default: '/api/data',
      label: { en: 'URL Path', zh: 'URL 路径' },
    },
  ],
  file: [
    {
      name: 'path',
      type: 'string',
      control: 'text',
      optional: false,
      default: 'data/sample.json',
      label: { en: 'File Path', zh: '文件路径' },
    },
    {
      name: 'fileType',
      type: 'string',
      control: 'select',
      optional: true,
      default: 'json',
      values: ['json', 'csv', 'lines'],
      label: { en: 'File Type', zh: '文件类型' },
    },
    {
      name: 'hasHeader',
      type: 'bool',
      control: 'radio',
      optional: true,
      default: true,
      label: { en: 'Has Header (CSV)', zh: '包含表头' },
    },
    {
      name: 'interval',
      type: 'int',
      control: 'text',
      optional: true,
      default: 1000,
      label: { en: 'Read Interval (ms)', zh: '读取间隔' },
    },
  ],
  redis: [
    {
      name: 'addr',
      type: 'string',
      control: 'text',
      optional: false,
      default: '127.0.0.1:6379',
      label: { en: 'Redis Address', zh: 'Redis 服务器地址' },
    },
    {
      name: 'password',
      type: 'string',
      control: 'text',
      optional: true,
      default: '',
      label: { en: 'Password', zh: '密码' },
    },
    {
      name: 'db',
      type: 'int',
      control: 'text',
      optional: true,
      default: 0,
      label: { en: 'Database', zh: '数据库编号' },
    },
  ],
  redisSub: [
    {
      name: 'addr',
      type: 'string',
      control: 'text',
      optional: false,
      default: '127.0.0.1:6379',
      label: { en: 'Redis Address', zh: 'Redis 服务器地址' },
    },
    {
      name: 'channels',
      type: 'string',
      control: 'list',
      optional: false,
      label: { en: 'Channels', zh: '订阅通道' },
    },
    {
      name: 'password',
      type: 'string',
      control: 'text',
      optional: true,
      default: '',
      label: { en: 'Password', zh: '密码' },
    },
    {
      name: 'db',
      type: 'int',
      control: 'text',
      optional: true,
      default: 0,
      label: { en: 'Database', zh: '数据库编号' },
    },
  ],
  neuron: [
    {
      name: 'url',
      type: 'string',
      control: 'text',
      optional: false,
      default: 'tcp://127.0.0.1:7081',
      label: { en: 'Neuron URL', zh: 'Neuron 地址' },
      hint: { en: 'Neuron NNG endpoint (e.g. tcp://127.0.0.1:7081)', zh: 'Neuron NNG 端点地址' },
    },
  ],
  websocket: [
    {
      name: 'url',
      type: 'string',
      control: 'text',
      optional: false,
      default: 'ws://127.0.0.1:8080/ws',
      label: { en: 'WebSocket URL', zh: 'WebSocket 地址' },
    },
  ],
  memory: [
    {
      name: 'topic',
      type: 'string',
      control: 'text',
      optional: false,
      default: 'devices/events',
      label: { en: 'Memory Topic', zh: '内存主题' },
    },
  ],
  simulator: [
    {
      name: 'data',
      type: 'string',
      control: 'textarea',
      optional: true,
      label: { en: 'Simulator JSON Data', zh: '模拟数据 JSON' },
    },
    {
      name: 'interval',
      type: 'int',
      control: 'text',
      optional: true,
      default: 1000,
      label: { en: 'Interval (ms)', zh: '间隔毫秒' },
    },
  ],
  can: [
    {
      name: 'network',
      type: 'string',
      control: 'select',
      optional: true,
      default: 'can',
      values: ['can', 'udp'],
      label: { en: 'Network', zh: '网络类型' },
      hint: { en: 'The network type of the CAN bus (can or udp)', zh: 'CAN总线的网络类型' },
    },
    {
      name: 'address',
      type: 'string',
      control: 'text',
      optional: false,
      default: 'can0',
      label: { en: 'Address', zh: '地址' },
      hint: { en: 'The device interface address of the CAN bus (e.g. can0)', zh: 'CAN总线的接口地址' },
    },
  ],
  video: [
    {
      name: 'url',
      type: 'string',
      control: 'text',
      optional: false,
      default: 'rtsp://127.0.0.1:554/live',
      label: { en: 'Stream URL', zh: '视频流地址' },
      hint: { en: 'RTSP or HTTP video stream endpoint', zh: 'RTSP 或 HTTP 视频流地址' },
    },
    {
      name: 'interval',
      type: 'int',
      control: 'text',
      optional: true,
      default: 1000,
      label: { en: 'Frame Interval (ms)', zh: '采样间隔毫秒' },
      hint: { en: 'Frame extraction rate interval in ms', zh: '抓帧间隔时间毫秒' },
    },
  ],
};

export const BUILTIN_SINK_PROPERTIES: Record<string, MetadataProperty[]> = {
  sql: [
    {
      name: 'url',
      type: 'string',
      control: 'text',
      optional: false,
      default: 'mysql://root:password@127.0.0.1:3306/test',
      label: { en: 'Database Connection URL', zh: '数据库连接 URL' },
      hint: { en: 'Target SQL database connection URL (e.g. mysql://user:pass@host:port/db)', zh: '目标数据库连接 URL' },
    },
    {
      name: 'table',
      type: 'string',
      control: 'text',
      optional: false,
      default: '',
      label: { en: 'Target Table Name', zh: '目标表名' },
    },
    {
      name: 'fields',
      type: 'string',
      control: 'list',
      optional: true,
      label: { en: 'Insert Column Names', zh: '插入列字段名列表' },
      hint: { en: 'Optional explicit column names to map output fields to table columns', zh: '可选的数据库写入列名' },
    },
  ],
  mqtt: [
    {
      name: 'server',
      type: 'string',
      control: 'text',
      optional: false,
      default: 'tcp://127.0.0.1:1883',
      label: { en: 'MQTT Broker Server', zh: 'MQTT 服务器地址' },
    },
    {
      name: 'topic',
      type: 'string',
      control: 'text',
      optional: false,
      default: 'analysis/result',
      label: { en: 'Publish Topic', zh: '发布主题' },
    },
    {
      name: 'protocolVersion',
      type: 'string',
      control: 'select',
      optional: true,
      default: '3.1.1',
      values: ['3.1.1', '3.1', '5.0'],
      label: { en: 'Protocol Version', zh: '协议版本' },
    },
    {
      name: 'clientid',
      type: 'string',
      control: 'text',
      optional: true,
      default: '',
      label: { en: 'Client ID', zh: '客户端 ID' },
    },
    {
      name: 'username',
      type: 'string',
      control: 'text',
      optional: true,
      default: '',
      label: { en: 'Username', zh: '用户名' },
    },
    {
      name: 'password',
      type: 'string',
      control: 'text',
      optional: true,
      default: '',
      label: { en: 'Password', zh: '密码' },
    },
    {
      name: 'qos',
      type: 'int',
      control: 'select',
      optional: true,
      default: 1,
      values: [0, 1, 2],
      label: { en: 'QoS', zh: '服务质量' },
    },
    {
      name: 'retained',
      type: 'bool',
      control: 'radio',
      optional: true,
      default: false,
      label: { en: 'Retained Message', zh: '保留消息' },
    },
    {
      name: 'insecureSkipVerify',
      type: 'bool',
      control: 'radio',
      optional: true,
      default: false,
      label: { en: 'Skip TLS Verify', zh: '跳过 TLS 检查' },
    },
  ],
  rest: [
    {
      name: 'url',
      type: 'string',
      control: 'text',
      optional: false,
      default: 'http://127.0.0.1:8080/api',
      label: { en: 'Endpoint URL', zh: '请求 URL' },
    },
    {
      name: 'method',
      type: 'string',
      control: 'select',
      optional: true,
      default: 'POST',
      values: ['POST', 'PUT', 'PATCH', 'GET', 'DELETE'],
      label: { en: 'HTTP Method', zh: 'HTTP 请求方法' },
    },
    {
      name: 'headers',
      type: 'object',
      control: 'list',
      optional: true,
      label: { en: 'HTTP Headers', zh: 'HTTP 消息头' },
    },
    {
      name: 'timeout',
      type: 'int',
      control: 'text',
      optional: true,
      default: 5000,
      label: { en: 'Timeout (ms)', zh: '超时时间' },
    },
    {
      name: 'sendSingle',
      type: 'bool',
      control: 'radio',
      optional: true,
      default: true,
      label: { en: 'Send Single Item', zh: '单条发送' },
    },
    {
      name: 'insecureSkipVerify',
      type: 'bool',
      control: 'radio',
      optional: true,
      default: false,
      label: { en: 'Skip TLS Verify', zh: '跳过 TLS 检查' },
    },
  ],
  http: [
    {
      name: 'url',
      type: 'string',
      control: 'text',
      optional: false,
      default: 'http://127.0.0.1:8080/api',
      label: { en: 'Endpoint URL', zh: '请求 URL' },
    },
    {
      name: 'method',
      type: 'string',
      control: 'select',
      optional: true,
      default: 'POST',
      values: ['POST', 'PUT', 'PATCH', 'GET', 'DELETE'],
      label: { en: 'HTTP Method', zh: '请求方法' },
    },
    {
      name: 'timeout',
      type: 'int',
      control: 'text',
      optional: true,
      default: 5000,
      label: { en: 'Timeout (ms)', zh: '超时毫秒' },
    },
  ],
  kafka: [
    {
      name: 'brokers',
      type: 'string',
      control: 'text',
      optional: false,
      default: '127.0.0.1:9092',
      label: { en: 'Kafka Brokers', zh: '服务节点' },
    },
    {
      name: 'topic',
      type: 'string',
      control: 'text',
      optional: false,
      default: '',
      label: { en: 'Publish Topic', zh: '发布主题' },
    },
    {
      name: 'saslAuthType',
      type: 'string',
      control: 'select',
      optional: true,
      default: 'none',
      values: ['none', 'plain', 'scram-sha-256', 'scram-sha-512'],
      label: { en: 'SASL Auth Type', zh: '认证机制' },
    },
    {
      name: 'saslUserName',
      type: 'string',
      control: 'text',
      optional: true,
      default: '',
      label: { en: 'SASL Username', zh: '用户名' },
    },
    {
      name: 'saslPassword',
      type: 'string',
      control: 'text',
      optional: true,
      default: '',
      label: { en: 'SASL Password', zh: '密码' },
    },
  ],
  file: [
    {
      name: 'path',
      type: 'string',
      control: 'text',
      optional: false,
      default: 'data/output.json',
      label: { en: 'File Path', zh: '输出文件路径' },
    },
    {
      name: 'fileType',
      type: 'string',
      control: 'select',
      optional: true,
      default: 'json',
      values: ['json', 'csv', 'lines'],
      label: { en: 'File Type', zh: '文件格式' },
    },
    {
      name: 'hasHeader',
      type: 'bool',
      control: 'radio',
      optional: true,
      default: true,
      label: { en: 'Has Header (CSV)', zh: '输出 CSV 表头' },
    },
    {
      name: 'rollingInterval',
      type: 'int',
      control: 'text',
      optional: true,
      default: 0,
      label: { en: 'Rolling Interval (ms)', zh: '轮转时间间隔' },
    },
    {
      name: 'rollingCount',
      type: 'int',
      control: 'text',
      optional: true,
      default: 0,
      label: { en: 'Rolling Count', zh: '轮转记录条数' },
    },
  ],
  edgex: [
    {
      name: 'protocol',
      type: 'string',
      control: 'select',
      optional: true,
      default: 'tcp',
      values: ['tcp', 'http', 'https'],
      label: { en: 'Protocol', zh: '协议' },
    },
    {
      name: 'server',
      type: 'string',
      control: 'text',
      optional: false,
      default: '127.0.0.1',
      label: { en: 'Server Host', zh: '服务器地址' },
    },
    {
      name: 'port',
      type: 'int',
      control: 'text',
      optional: false,
      default: 5566,
      label: { en: 'Port', zh: '端口' },
    },
    {
      name: 'type',
      type: 'string',
      control: 'select',
      optional: false,
      default: 'redis',
      values: ['redis', 'mqtt', 'zero'],
      label: { en: 'Bus Type', zh: '总线类型' },
    },
    {
      name: 'topic',
      type: 'string',
      control: 'text',
      optional: true,
      default: 'events',
      label: { en: 'Topic', zh: '主题' },
    },
  ],
  redis: [
    {
      name: 'addr',
      type: 'string',
      control: 'text',
      optional: false,
      default: '127.0.0.1:6379',
      label: { en: 'Redis Address', zh: 'Redis 地址' },
    },
    {
      name: 'password',
      type: 'string',
      control: 'text',
      optional: true,
      default: '',
      label: { en: 'Password', zh: '密码' },
    },
    {
      name: 'db',
      type: 'int',
      control: 'text',
      optional: true,
      default: 0,
      label: { en: 'Database', zh: '数据库编号' },
    },
    {
      name: 'topic',
      type: 'string',
      control: 'text',
      optional: true,
      default: '',
      label: { en: 'Publish Channel', zh: '发布频道' },
    },
    {
      name: 'key',
      type: 'string',
      control: 'text',
      optional: true,
      default: '',
      label: { en: 'Cache Key', zh: '缓存键名' },
    },
    {
      name: 'dataType',
      type: 'string',
      control: 'select',
      optional: true,
      default: 'string',
      values: ['string', 'list', 'set'],
      label: { en: 'Data Type', zh: '数据类型' },
    },
  ],
  redisPub: [
    {
      name: 'addr',
      type: 'string',
      control: 'text',
      optional: false,
      default: '127.0.0.1:6379',
      label: { en: 'Redis Address', zh: 'Redis 地址' },
    },
    {
      name: 'topic',
      type: 'string',
      control: 'text',
      optional: false,
      default: '',
      label: { en: 'Publish Channel', zh: '发布频道' },
    },
    {
      name: 'password',
      type: 'string',
      control: 'text',
      optional: true,
      default: '',
      label: { en: 'Password', zh: '密码' },
    },
  ],
  tdengine: [
    {
      name: 'url',
      type: 'string',
      control: 'text',
      optional: false,
      default: 'taos://root:taosdata@127.0.0.1:6030/test',
      label: { en: 'TDengine URL', zh: 'TDengine 连接地址' },
    },
    {
      name: 'table',
      type: 'string',
      control: 'text',
      optional: false,
      default: '',
      label: { en: 'Table Name', zh: '目标表名' },
    },
  ],
  influx: [
    {
      name: 'addr',
      type: 'string',
      control: 'text',
      optional: false,
      default: 'http://127.0.0.1:8086',
      label: { en: 'InfluxDB Server', zh: 'InfluxDB 服务器地址' },
    },
    {
      name: 'measurement',
      type: 'string',
      control: 'text',
      optional: false,
      default: '',
      label: { en: 'Measurement', zh: '度量名称' },
    },
    {
      name: 'token',
      type: 'string',
      control: 'text',
      optional: true,
      default: '',
      label: { en: 'Token', zh: '访问令牌' },
    },
    {
      name: 'org',
      type: 'string',
      control: 'text',
      optional: true,
      default: '',
      label: { en: 'Organization', zh: '组织名称' },
    },
    {
      name: 'bucket',
      type: 'string',
      control: 'text',
      optional: true,
      default: '',
      label: { en: 'Bucket', zh: 'Bucket 名称' },
    },
  ],
  neuron: [
    {
      name: 'url',
      type: 'string',
      control: 'text',
      optional: false,
      default: 'tcp://127.0.0.1:7081',
      label: { en: 'Neuron URL', zh: 'Neuron 地址' },
    },
    {
      name: 'nodeName',
      type: 'string',
      control: 'text',
      optional: false,
      default: '',
      label: { en: 'Node Name', zh: '节点名称' },
    },
    {
      name: 'groupName',
      type: 'string',
      control: 'text',
      optional: false,
      default: '',
      label: { en: 'Group Name', zh: '组名称' },
    },
  ],
  websocket: [
    {
      name: 'url',
      type: 'string',
      control: 'text',
      optional: false,
      default: 'ws://127.0.0.1:8080/ws',
      label: { en: 'WebSocket URL', zh: 'WebSocket 目标地址' },
    },
  ],
  log: [
    {
      name: 'logLevel',
      type: 'string',
      control: 'select',
      optional: true,
      default: 'INFO',
      values: ['DEBUG', 'INFO', 'WARN', 'ERROR'],
      label: { en: 'Log Level', zh: '日志输出等级' },
    },
  ],
  memory: [
    {
      name: 'topic',
      type: 'string',
      control: 'text',
      optional: false,
      default: 'results',
      label: { en: 'Topic', zh: '内存主题' },
    },
  ],
  nop: [
    {
      name: 'log',
      type: 'bool',
      control: 'radio',
      optional: true,
      default: false,
      label: { en: 'Log Enabled', zh: '是否打印日志' },
    },
  ],
  image: [
    {
      name: 'path',
      type: 'string',
      control: 'text',
      optional: false,
      default: './tmp',
      label: { en: 'Storage Path', zh: '存储路径' },
      hint: { en: 'Folder path for storing pictures (e.g. ./tmp)', zh: '保存图片的文件夹名，例如 ./tmp' },
    },
    {
      name: 'imageFormat',
      type: 'string',
      control: 'select',
      optional: true,
      default: 'jpeg',
      values: ['jpeg', 'png'],
      label: { en: 'Format', zh: '图片格式' },
      hint: { en: 'File format, supports jpeg and png', zh: '文件格式，支持 jpeg 和 png' },
    },
    {
      name: 'maxAge',
      type: 'int',
      control: 'text',
      optional: true,
      default: 72,
      label: { en: 'Max Retention (hours)', zh: '最长保留时间 (小时)' },
      hint: { en: 'Maximum file storage time in hours (default 72h)', zh: '最长文件存储时间(小时)' },
    },
    {
      name: 'maxCount',
      type: 'int',
      control: 'text',
      optional: true,
      default: 1000,
      label: { en: 'Max Image Count', zh: '最大写入数量' },
      hint: { en: 'Maximum number of images before older ones are pruned', zh: '存储图片的最大数量，超过后删除较早图片' },
    },
  ],
  influx2: [
    {
      name: 'addr',
      type: 'string',
      control: 'text',
      optional: false,
      default: 'http://127.0.0.1:8086',
      label: { en: 'InfluxDB v2 Address', zh: 'InfluxDB v2 服务地址' },
      hint: { en: 'InfluxDB 2.x HTTP URL endpoint', zh: 'InfluxDB 2.x 服务的 HTTP 地址' },
    },
    {
      name: 'bucket',
      type: 'string',
      control: 'text',
      optional: false,
      default: '',
      label: { en: 'Bucket', zh: '存储桶 (Bucket)' },
      hint: { en: 'InfluxDB target bucket name', zh: '目标 Bucket 名称' },
    },
    {
      name: 'org',
      type: 'string',
      control: 'text',
      optional: false,
      default: '',
      label: { en: 'Organization', zh: '组织 (Org)' },
      hint: { en: 'InfluxDB organization name', zh: 'InfluxDB 组织名称' },
    },
    {
      name: 'token',
      type: 'string',
      control: 'text',
      optional: true,
      default: '',
      label: { en: 'API Token', zh: '访问令牌 (Token)' },
      hint: { en: 'InfluxDB API authentication token', zh: 'InfluxDB 访问授权 Token' },
    },
    {
      name: 'measurement',
      type: 'string',
      control: 'text',
      optional: false,
      default: '',
      label: { en: 'Measurement', zh: '度量名称 (Measurement)' },
      hint: { en: 'InfluxDB measurement metric key', zh: 'InfluxDB measurement 度量名称' },
    },
    {
      name: 'precision',
      type: 'string',
      control: 'select',
      optional: false,
      default: 'ms',
      values: ['s', 'ms', 'us', 'ns'],
      label: { en: 'Time Precision', zh: '时间精度' },
      hint: { en: 'Timestamp resolution precision', zh: '时间戳时间精度' },
    },
    {
      name: 'useLineProtocol',
      type: 'bool',
      control: 'radio',
      optional: true,
      default: false,
      label: { en: 'Use Line Protocol', zh: '使用行协议' },
      hint: { en: 'Format output payload according to Influx line protocol', zh: '按照 InfluxDB 行协议格式输出' },
    },
  ],
};

/**
 * Returns fallback schema properties for a given connector category and type.
 */
export function getBuiltinConnectorProperties(
  category: 'sources' | 'sinks' | 'connections',
  type: string
): MetadataProperty[] {
  const normType = (type || '').toLowerCase().trim();
  if (category === 'connections') {
    return (
      BUILTIN_SOURCE_PROPERTIES[normType]?.filter((p) => p.name !== 'connectionSelector') ||
      BUILTIN_SINK_PROPERTIES[normType]?.filter((p) => p.name !== 'connectionSelector') ||
      []
    );
  }
  if (category === 'sinks') {
    return (
      BUILTIN_SINK_PROPERTIES[normType] ||
      BUILTIN_SOURCE_PROPERTIES[normType]?.filter((p) => p.name !== 'connectionSelector') ||
      []
    );
  }
  return BUILTIN_SOURCE_PROPERTIES[normType] || [];
}
